groupie/urls.py
import re

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()


def static(prefix, **kwargs):
    return patterns('',
        url(r'^%s(?P<path>.*)$' % re.escape(prefix.lstrip('/')),
            'django.views.static.serve', kwargs=kwargs),
    )

urlpatterns = patterns('',
    url(r'^$', 'groupie.app.views.home', name='home'),
    url(r'^deadline_hack/(?P<voting_hash>[a-zA-Z0-9]{8})$', 'groupie.app.views.deadline_hack', name='deadline_hack'),
    url(r'^(?P<voting_hash>[a-zA-Z0-9]{8})$', 'groupie.app.views.voting', name='voting'),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

groupie/app/models.py
# -*- coding: utf-8 -*-
import random
import string

from django.db import models


## VOTING ##

def generate_hash():
    while True:
        url_hash = ''.join(random.sample(string.ascii_letters + string.digits, 8))
        if not Voting.objects.filter(url_hash=url_hash).exists():
            return url_hash


class Voting(models.Model):
    url_hash = models.CharField(primary_key=True, max_length=8,
                                default=generate_hash, editable=False)
    from_email = models.EmailField(max_length=255)
    description = models.TextField()
    deadline = models.DateTimeField(blank=True, null=True)

    notify_create_at = models.DateTimeField(blank=True, null=True)
    notify_deadline_at = models.DateTimeField(blank=True, null=True)
    notify_half_voted_at = models.DateTimeField(blank=True, null=True)
    notify_all_voted_at = models.DateTimeField(blank=True, null=True)

    def __unicode__(self):
        """
        Returns a snapshot of current scores.
        """
        # TODO: makes some smart aggregation here
        # and basically check all other places where related managers are called...
        scores = ["{} [{}]".format(o, o.voters.count()) for o in self.voting_options.all()]
        return u', '.join(scores)

    @property
    def creator(self):
        return self.voters.get(email=self.from_email)

    @property
    def description_short(self, length=50):
        short = self.description[:50]
        return u"{}...".format(short)


## VOTING OPTION ##

class VotingOption(models.Model):
    voting = models.ForeignKey(Voting, related_name='voting_options')

    option = models.DateTimeField()

    def __unicode__(self):
        return unicode(self.option)


## VOTER ##


def generate_ref():
    while True:
        ref_hash = ''.join(random.sample(string.ascii_letters + string.digits, 8))
        if not Voter.objects.filter(ref_hash=ref_hash).exists():
            return ref_hash


class Voter(models.Model):
    voting = models.ForeignKey(Voting, related_name='voters')
    voted_voting_options = models.ManyToManyField(VotingOption, related_name='voters')

    ref_hash = models.CharField(primary_key=True, max_length=8, default=generate_ref, editable=False)
    email = models.EmailField()

    def __unicode__(self):
        return u'{}'.format(self.email)

groupie/app/templates/base.html
{% load staticfiles %}
{% load compressed %}
<!DOCTYPE html>
<html>
  <head>
    <title>Groupie manager</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% compressed_css 'bootstrap' %}
    {% compressed_css 'groupie' %}

    <script src="//code.jquery.com/jquery.js"></script>
    <!--[if lt IE 9]>
      <script src="{% static 'lib/html5shiv/js/html5shiv.js' %}"></script>
      <script src="{% static 'lib/respond/js/respond.js' %}"></script>
    <![endif]-->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <link rel="apple-touch-icon" href="{% static 'img/apple-touch-icon.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/apple-touch-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/apple-touch-icon-114x114.png' %}">

    {% compressed_js 'libs' %}
  </head>
  <body class="{% block body_classes %}{% endblock %}">
  
  <div class="jumbotron italy">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 title">
          <a href="{% url 'home' %}">
            <h1>Welcome to Groupie!</h1>
          </a>
          <h4>Manage group ideas for events, trips and everything else!</h4>
        </div>
        {% block form %}{% endblock %}
      </div>
    </div>
  </div>

  {% block main %}{% endblock %}
  
  {% block footer %}
  <footer>
    <div class="container">
      <div class="row">
        <hr class="col-sm-12 divisor">
      </div>
      <div class="row">
      <div class="col-sm-10">© 2013 Groupie manager</div>
      <div class="col-sm-2 text-right"><a href="http://djangodash.com/teams/c4/puccis/">Django Dash 2013</a></div>
      </div>
    </div>
  </footer>
  {% endblock %}

  {% compressed_js 'bootstrap' %}
  {% compressed_js 'groupie' %}
  </body>
</html>

groupie/app/templates/home.html
{% extends "base.html" %}
{% load staticfiles jstemplate %}

{% block form %}

{% mustachejs "datetimepicker" %}

<div class="col-lg-5 form-style">
  <form role="form" action="{% url 'home' %}" method="post">
    {% csrf_token %}
    <div class="form-group col-md-12 {% if form.from_email.errors %}has-error{% endif %}">
      <label class="control-label" for="id_from_email">Your email</label>
      <div>
        <input class="form-control input-sm" id="id_from_email" maxlength="255"
               name="from_email" type="email" placeholder="you@yourserver.com" value="{{ form.from_email.value }}" />
        {% if form.from_email.errors %}
        <span class="alert alert-danger">{{ form.from_email.errors.0 }}</span>
        {% endif %}
      </div>
    </div>
    <div class="form-group col-md-12 {% if form.description.errors %}has-error{% endif %}">
      <label class="control-label" for="id_description">What is your proposal?</label>
      <div class="">
        <textarea class="form-control input-sm" cols="40" id="id_description" name="description" rows="4"
                  placeholder="Describe your planned activity here...">{{ form.description.value }}</textarea>
        {% if form.description.errors %}
        <span class="alert alert-danger">{{ form.description.errors.0 }}</span>
        {% endif %}
      </div>
    </div>

    <div class="form-group col-md-12 {% if form.errors.voting_options %}has-error{% endif %}">
      <label class="control-label" for="voting_option_{{ forloop.counter0 }}">When do you want to do it?</label>
      {% for value in voting_options %}
      {% if forloop.first %}
      <div id="initial_option" class="row voting-option">
      {% else %}
      <div class="row voting-option">
      {% endif %}
        <div class="input-append date col-xs-8 input" id="voting_option_{{ forloop.counter0 }}" data-date-format="dd/mm/yyyy hh:ii">
          <input class="form-control input-sm" name="voting_options" size="16" type="text" value="{{ value|date:'d/m/Y H:i' }}" placeholder="30/09/2013 18:00" />
          <span class="add-on"><i class="icon-th"></i></span>
        </div>
        {% if not forloop.first %}
        <a class="btn btn-danger remove col-xs-3" type="button">Remove</a>
        {% endif %}
        {% if forloop.first %}
        <a class="btn btn-default col-xs-3" id="add-datepair">Add another</a>
        {% endif %}
      </div>
      {% empty %}
      <div id="initial_option" class="row voting-option">
        <div class="input-append date col-xs-8" id="voting_option_0" data-date-format="dd/mm/yyyy hh:ii">
          <input class="form-control input-xs" name="voting_options" size="16" type="text" placeholder="30/09/2013 18:00" />
          <span class="add-on"><i class="icon-th"></i></span>
        </div>
        <a class="btn btn-default col-xs-3" disabled="disabled" id="add-datepair">Add another</a>
      </div>
      {% if form.errors.voting_options %}
      <div class="row">
        <div class="col-xs-12">
          <span class="alert alert-danger">{{ form.errors.voting_options.0 }}</span>
        </div>
      </div>
      {% endif %}
      {% endfor %}
    </div>

    <div class="form-group col-md-12 {% if form.emails.errors %}has-error{% endif %}">
      <label class="control-label" for="id_emails">Who do you want to invite?</label>
      <div>
        <input class="form-control input-sm" id="id_emails" name="emails" type="text" value="{{ emails }}" placeholder="List here emails of your buddies" />
        {% if form.emails.errors %}
        <span class="alert alert-danger">{{ form.emails.errors.0 }}</span>
        {% endif %}
        <p class="help-block">Enter email addresses, press enter after each of them</p>
      </div>
    </div>

    <div class="form-group col-md-12 {% if form.deadline.errors %}has-error{% endif %}">
      <label class="control-label" for="voting_deadline">Voting deadline (optional)</label>
      <div class="input-append date" id="voting_deadline" data-date-format="dd/mm/yyyy hh:ii">
        <input class="form-control input-sm" size="16" name="deadline" type="text"
               value="{{ form.deadline.value }}" placeholder="29/09/2013 22:00" />
        {% if form.deadline.errors %}
        <span class="alert alert-danger">{{ form.deadline.errors.0 }}</span>
        {% endif %}
        <span class="add-on"><i class="icon-th"></i></span>
      </div>
    </div>

    <div class="form-group">
      <input class="btn btn-primary btn-lg btn-block" type="submit" name="create" value="create" />
    </div>
  </form>
</div>
{% endblock %}

{% block footer %}
<div class="dark">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h3>How it works</h3>
        <h4>Enter the emails of your friends, propose a date and see what they think about it!</h4>
      </div>
    </div>
  </div>
</div>
<div class="container how-it-works">
  <div class="row">
    <div class="col-sm-4">
      <img src="{% static 'img/organize-icon.png' %}">
      <h4>Organize group events<br> and trips</h4>
    </div>
    <div class="col-sm-4">
      <img src="{% static 'img/comments-icon.png' %}">
      <h4>Add comments directly<br> from email <em>** soon</em></h4>
    </div>
    <div class="col-sm-4">
      <img src="{% static 'img/notifications-icon.png' %}">
      <h4>Send reminders and summary emails to everybody in the group</h4>
    </div>
  </div>
</div>
{{ block.super }}
{% endblock %}

groupie/app/templates/voting.html
{% extends "base.html" %}
{% load jstemplate %}

{% block body_classes %}voting{% endblock %}

{% block main %}
{% mustachejs "voters" %}

<div class="container">
  {% for message in messages %}
  <div class="alert alert-dismissable alert-{{ message.tags }}">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <p>{{ message }}</p>
  </div>
  {% endfor %}

  <form action="{% url 'voting' voting.url_hash %}?ref={{ voter.ref_hash }}" method="post">
    {% csrf_token %}
    
    <div class="row">
      <div class="col-lg-12">
        {% if is_creator %}
        <h3>You asked your friends what's their preference when to do <em>{{ voting.description }}</em></h3>
        {% if voting.deadline %}
        <p>Voting deadline is <strong>{{ voting.deadline|date:'d/m/Y H:i' }} </strong></p>
        {% endif %}
        {% else %}
      	<h2>{{ voting.creator.email }}</h2>
      	<h4>Wants to know what do you think about <em>{{ voting.description }}</em></h4>
        {% if voting.deadline %}
        <p>Please fill out this form until <strong>{{ voting.deadline|date:'d/m/Y H:i' }}</strong>, after that voting will be closed...</p>
        {% endif %}
        {% endif %}
      </div>
    </div>

    <div class="row">
      {% if not is_creator %}
      <div class="col-lg-12">
      	<p>Click on all the time options when you are available:</p>
      </div>
      {% endif %}
      {% for option in voting_options %}
      <div class="col-sm-6 col-md-3">
        <div class="panel panel-default vote-{{ option.vote }} voting-option" data-option="{{ option.id }}">
          <div class="panel-body">
            <h4 class="text-center">{{ option.datetime|date:'d/m/Y' }}</h4>
            <h2 class="text-center">{{ option.datetime|date:'H:i' }}</h2>
          </div>
          <div class="panel-footer">
            <span class="nr_of_votes text-center" data-voters="{{ option.voters }}" data-nr-of-votes="{{ option.nr_of_votes }}">
              {{ option.nr_of_votes }} vote{{ option.nr_of_votes|pluralize }}
            </span>
          </div>
        </div>
        </div>
      {% endfor %}
    </div>
    <div class="row">
      <div class="col-md-3 btn-send-vote">
        {% if is_creator %}
        <input id="change-vote" class="btn btn-primary btn-lg btn-block" disabled="disabled" type="submit" value="Change your vote" />
        {% else %}
        <input class="btn btn-primary btn-lg btn-block" type="submit" value="Submit your vote" />
        <p class="text-danger"><small>* If you cannot make it then submit an empty form</small></p>
        {% endif %}
      </div>
    </div>
    <div class="row" style="display: none">
      <div class="col-lg-12">
        {{ form.as_table }}
      </div>
    </div>
  </form>
</div>
{% endblock main %}